### ISSUE TITLE
People name tag can be off the frame

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#11]
Ideally, the name tag should be relative to the image frame position, and not float based on the device type:

![image](https://user-images.githubusercontent.com/4111337/51082555-041b3500-16be-11e9-8c5a-e0650c07530a.png)

However, if we look at [multi-device simulator](https://www.responsinator.com/?url=https%3A%2F%2Fjsy1218.github.io%2Fcypa-yeps-website%2F), we can see some device screen have the name tag off the frame.

![image](https://user-images.githubusercontent.com/4111337/51082551-d9c97780-16bd-11e9-8499-ee8df3034ec1.png)

**Comment by Nini0415** [comment]
PR submitted
https://github.com/jsy1218/cypa-yeps-website/pull/17
