### ISSUE TITLE
NavBar background color is wrong

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#21]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/52976224-83ff8380-337d-11e9-9983-2877f07b8ab3.png)

Current UI:

![image](https://user-images.githubusercontent.com/4111337/52976264-a09bbb80-337d-11e9-83f2-0a085af066a3.png)

**Comment by Nini0415** [comment]
The current navbar bg color is more consistent with the logo's color, can we talk with the designer to see if we want to follow the origin color scheme. Also for the button, I know it's not the same yellow as the design, but it's a yellow bootstrap provide, which means we don't need to hack the button color.

**Comment by jsy1218** [comment]
I'm ok with button color. But blue navbar bg color looks weird on desktop rendering. Although we can talk to the designer, it is likely to be re-design for the desktop context.

**Comment by jsy1218** [comment]
No longer applies due to design change:

![image](https://user-images.githubusercontent.com/4111337/56761442-2b1fe300-6752-11e9-986b-86c5efa77690.png)
