### ISSUE TITLE
Keynotes desktop 3 sections didn't show the vertical line to seperate as per design, resulting in crunchness

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#22]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/52976390-33d4f100-337e-11e9-9e75-79c68cdc9404.png)

Current design:

![image](https://user-images.githubusercontent.com/4111337/52976324-ec4e6500-337d-11e9-9a88-cd4be66c3e60.png)

Please note how the Zeplin design has two vertical bars in between three sections, and make sections more seperated as appropriate.

Please do some research on whether there is open-source library for this particular layout. I expect more than css change.

**Comment by Nini0415** [comment]
Haven't found a good lib yet, will try later. Merge the css files first. Another big defect with this page is the globe icon image is not consistent with the other two. Please provide the correct globe icon image.

**Comment by jsy1218** [comment]
I think this will be a difficult change, hence staying as is.
