### ISSUE TITLE
NavBar font only appropriate for mobile view, too small for desktop view

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#23]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/52976224-83ff8380-337d-11e9-9983-2877f07b8ab3.png)

Current UI:

![image](https://user-images.githubusercontent.com/4111337/52976264-a09bbb80-337d-11e9-83f2-0a085af066a3.png)

**Comment by Nini0415** [comment]
Will try some adjustment later, but I assume your screenshot is from a large monitor, since the button looks super small from your screenshot.

**Comment by jsy1218** [comment]
Fixed as part of the design change:

![image](https://user-images.githubusercontent.com/4111337/56767601-01ba8380-6761-11e9-92e9-926f7730d25d.png)
