### ISSUE TITLE
Please use react-device-detect library to determine the device type

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#28]
https://github.com/jsy1218/cypa-yeps-website/pull/20/files/dc111c1bb29743a91b55104e4d7612bc6fc4743d#diff-38682f47b0cf12c516bc3714fc45d0fd

**Comment by Nini0415** [comment]
PR submitted
https://github.com/jsy1218/cypa-yeps-website/pull/32

**Comment by jsy1218** [comment]
Fixed
