### ISSUE TITLE
Deploy the site to HostGator

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#30]

**Comment by jsy1218** [comment]
We have deployed the site to HostGator DNS provider, which the DNS resolves to yeps.globalcypa.org. We have a lightweight mechanism to manually deploy to the HostGator, and we are not looking to automate as of now.

**Comment by auspicious1123** [comment]
Can you please remove me from the subscription list?

Thanks!

**Comment by jsy1218** [comment]
Only you can disable git notification yourself, by unwatching the
repository.

Rui Wang <notifications@github.com> 于2019年4月15日周一 下午12:12写道：

> Can you please remove me from the subscription list?
>
> Thanks!
>
> Sent from my iPhone
>
