### ISSUE TITLE
Make language button and collapsible menu black, and consistent with logo color 

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#6]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/50112364-edcfa580-01f3-11e9-8377-a53260fe0913.png)

Current implementation:

![image](https://user-images.githubusercontent.com/4111337/50112396-fe801b80-01f3-11e9-8bfe-8377a16435c7.png)

**Comment by Nini0415** [comment]
PR submitted:
https://github.com/jsy1218/cypa-yeps-website/pull/15
