### ISSUE TITLE
Wave width should nicely fit the screen width

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#7]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/50112531-4141f380-01f4-11e9-992c-f31ee61142b5.png)

Current implementation:

![image](https://user-images.githubusercontent.com/4111337/50112566-54ed5a00-01f4-11e9-892c-c33fe29f8374.png)

**Comment by Nini0415** [comment]
PR submitted
#14
