### ISSUE TITLE
Top Section div width should be wider

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#8]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/50112900-48b5cc80-01f5-11e9-9389-e38b5f7856bb.png)

Current implementation:

![image](https://user-images.githubusercontent.com/4111337/50112914-53706180-01f5-11e9-91bc-38c297f33a91.png)

**Comment by Nini0415** [comment]
PR submitted
https://github.com/jsy1218/cypa-yeps-website/pull/14

**Comment by Nini0415** [comment]
PR submitted:
https://github.com/jsy1218/cypa-yeps-website/pull/19
