### ISSUE TITLE
Try make text alignment both left and right for Keynotes

### ISSUE THREAD

**Issue by jsy1218** [jsy1218/cypa-yeps-website#9]
Zeplin design:

![image](https://user-images.githubusercontent.com/4111337/50112987-8f0b2b80-01f5-11e9-9e24-adc35b7a7a0d.png)

Current implementation:

![image](https://user-images.githubusercontent.com/4111337/50113009-9df1de00-01f5-11e9-9e56-e818d40051b0.png)

**Comment by Nini0415** [comment]
PR submitted
https://github.com/jsy1218/cypa-yeps-website/pull/18
